name: Send Lesson Reminders

on:
  schedule:
    - cron: "*/5 * * * *" # ყოველ 5 წუთში
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reminders API
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" "https://evectus.ge/api/reminders/send-lesson-reminders")
          if [ "$response_code" -eq 200 ]; then
            echo "✅ რემაინდერები გაიგზავნა წარმატებით"
          else
            echo "❌ ვერ გაიგზავნა რემაინდერები. HTTP Status: $response_code"
            exit 1
          fi
