name: Send Lesson Reminders

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reminders API
        run: curl -X GET "https://evectus.ge/api/reminders/send-lesson-reminders"
